# 定義整個 cloud build 作業需要做哪些事、每個 name args 是指用哪個名稱(name)的映像檔去下哪些指令(args)
steps:

  # 使用 gcp cloud build 提供的叫做 gcr.io/cloud-builders/mvn 的映像檔來做接下來這個步驟要做的事，如下說明：
  # 等於下 "mvn clean install -DskipTests" 這個指令
  # 意思是 先把專案中之前編譯產生的舊檔案刪掉，接著打包並安裝 jar 到本地 maven 倉庫
  # ( 這裡的本地倉庫是指用來打包的環境的本地 maven 倉庫 )
  - name: 'asia-east1-docker.pkg.dev/$PROJECT_ID/forchangandrouchat/custom-maven:latest'
    args: ['clean', 'install', '-DskipTests']

  # 使用 gcp cloud build 提供的叫做 gcr.io/cloud-builders/docker 的映像檔來做接下來這個步驟要做的事，如下說明：
  # 等於下 "docker build -t gcr.io/$PROJECT_ID/my-springboot-app ." 這個指令
  # 意思是把此專案建立成一個叫做gcr.io/專案名稱/my-springboot-app 的 docker image，
  # 並且建立映像檔要依據的 Dockerfile 在目前資料夾，也就是專案根目錄
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/forchangandrouchat/forchangandrouchatapp', '.' ]

  # 使用 gcp cloud build 提供的叫做 gcr.io/cloud-builders/docker 的映像檔來做接下來這個步驟要做的事，如下說明：
  # 等於下 "docker push gcr.io/$PROJECT_ID/my-springboot-app" 這個指令
  # 意思是把上一個步驟建立好的專案的映像檔推送到 gcr.io/$PROJECT_ID/ 這個位置，叫做 my-springboot-app
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/forchangandrouchat/forchangandrouchatapp' ]

  # 使用 gcp cloud build 提供的叫做 gcr.io/cloud-builders/gcloud 的映像檔來做接下來這個步驟要做的事，如下說明：
  # 等於下 "gcloud run deploy my-springboot-app" 這個指令，並且做以下個別設定：
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'forchangandrouchat',
        '--image', # 這行跟下一行在指定要部署的映像檔是哪個
        'asia-east1-docker.pkg.dev/$PROJECT_ID/forchangandrouchat/forchangandrouchatapp',
        '--region', # region asia-east1 是指定程式要部署到哪個區域的資料中心
        'asia-east1',
        '--platform', # platform managed 是指使用完全託管(fully-managed)模式的 cloud run
        'managed',
        '--allow-unauthenticated' # 允許任何人直接存取，如果要限制存取，把這參數移除或改成其他 IAM 設定
      ]

# 此區塊不是整個流程中的步驟，作用是告訴 cloud build 在 cicd 流程最後的產出裡，要列出哪些 docker 映像檔
# 在 cloud build 的介面上看 build artifact，就會看到這逼設定的名稱
# 不加這行也可正常運作，只是有加的話可讀性會比較高
images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/forchangandrouchat/forchangandrouchatapp'

options:
  logging: CLOUD_LOGGING_ONLY